//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReferencePhotos
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTO", Namespace="http://schemas.datacontract.org/2004/07/MyPhotosP2", IsReference=true)]
    public partial class DTO : object
    {
        
        private int IdField;
        
        private string PathField;
        
        private string PozaSauVideoField;
        
        private string StersField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Path
        {
            get
            {
                return this.PathField;
            }
            set
            {
                this.PathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PozaSauVideo
        {
            get
            {
                return this.PozaSauVideoField;
            }
            set
            {
                this.PozaSauVideoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sters
        {
            get
            {
                return this.StersField;
            }
            set
            {
                this.StersField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Proprietati", Namespace="http://schemas.datacontract.org/2004/07/MyPhotosP2", IsReference=true)]
    public partial class Proprietati : object
    {
        
        private int IdField;
        
        private System.Collections.Generic.List<ServiceReferencePhotos.Media> MediaField;
        
        private string NumeCampField;
        
        private string ValoareCampField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ServiceReferencePhotos.Media> Media
        {
            get
            {
                return this.MediaField;
            }
            set
            {
                this.MediaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeCamp
        {
            get
            {
                return this.NumeCampField;
            }
            set
            {
                this.NumeCampField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ValoareCamp
        {
            get
            {
                return this.ValoareCampField;
            }
            set
            {
                this.ValoareCampField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Media", Namespace="http://schemas.datacontract.org/2004/07/MyPhotosP2", IsReference=true)]
    public partial class Media : object
    {
        
        private int IdField;
        
        private string PathField;
        
        private string PozaSauVideoField;
        
        private System.Collections.Generic.List<ServiceReferencePhotos.Proprietati> ProprietatisField;
        
        private string StersField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Path
        {
            get
            {
                return this.PathField;
            }
            set
            {
                this.PathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PozaSauVideo
        {
            get
            {
                return this.PozaSauVideoField;
            }
            set
            {
                this.PozaSauVideoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ServiceReferencePhotos.Proprietati> Proprietatis
        {
            get
            {
                return this.ProprietatisField;
            }
            set
            {
                this.ProprietatisField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sters
        {
            get
            {
                return this.StersField;
            }
            set
            {
                this.StersField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferencePhotos.InterfaceApi")]
    public interface InterfaceApi
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceApi/PreluarePoza", ReplyAction="http://tempuri.org/InterfaceApi/PreluarePozaResponse")]
        System.Threading.Tasks.Task PreluarePozaAsync(string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceApi/AdaugaProprietate", ReplyAction="http://tempuri.org/InterfaceApi/AdaugaProprietateResponse")]
        System.Threading.Tasks.Task AdaugaProprietateAsync(string path, string nume, string valoare);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceApi/StergeProprietate", ReplyAction="http://tempuri.org/InterfaceApi/StergeProprietateResponse")]
        System.Threading.Tasks.Task StergeProprietateAsync(string path, string nume, string valoare);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceApi/SchimbaProprietate", ReplyAction="http://tempuri.org/InterfaceApi/SchimbaProprietateResponse")]
        System.Threading.Tasks.Task SchimbaProprietateAsync(string nume, string valoare);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceApi/StergePoza", ReplyAction="http://tempuri.org/InterfaceApi/StergePozaResponse")]
        System.Threading.Tasks.Task StergePozaAsync(string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceApi/Cautare", ReplyAction="http://tempuri.org/InterfaceApi/CautareResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceReferencePhotos.DTO>> CautareAsync(string nume, string valoare);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceApi/GetAllPhotos", ReplyAction="http://tempuri.org/InterfaceApi/GetAllPhotosResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceReferencePhotos.DTO>> GetAllPhotosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceApi/GetAllProp", ReplyAction="http://tempuri.org/InterfaceApi/GetAllPropResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceReferencePhotos.Proprietati>> GetAllPropAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceApi/CautarePropPhoto", ReplyAction="http://tempuri.org/InterfaceApi/CautarePropPhotoResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceReferencePhotos.Proprietati>> CautarePropPhotoAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceApi/MaxIdMedia", ReplyAction="http://tempuri.org/InterfaceApi/MaxIdMediaResponse")]
        System.Threading.Tasks.Task<int> MaxIdMediaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceApi/MaxIdProp", ReplyAction="http://tempuri.org/InterfaceApi/MaxIdPropResponse")]
        System.Threading.Tasks.Task<int> MaxIdPropAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    public interface InterfaceApiChannel : ServiceReferencePhotos.InterfaceApi, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    public partial class InterfaceApiClient : System.ServiceModel.ClientBase<ServiceReferencePhotos.InterfaceApi>, ServiceReferencePhotos.InterfaceApi
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public InterfaceApiClient() : 
                base(InterfaceApiClient.GetDefaultBinding(), InterfaceApiClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_InterfaceApi.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public InterfaceApiClient(EndpointConfiguration endpointConfiguration) : 
                base(InterfaceApiClient.GetBindingForEndpoint(endpointConfiguration), InterfaceApiClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public InterfaceApiClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(InterfaceApiClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public InterfaceApiClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(InterfaceApiClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public InterfaceApiClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task PreluarePozaAsync(string path)
        {
            return base.Channel.PreluarePozaAsync(path);
        }
        
        public System.Threading.Tasks.Task AdaugaProprietateAsync(string path, string nume, string valoare)
        {
            return base.Channel.AdaugaProprietateAsync(path, nume, valoare);
        }
        
        public System.Threading.Tasks.Task StergeProprietateAsync(string path, string nume, string valoare)
        {
            return base.Channel.StergeProprietateAsync(path, nume, valoare);
        }
        
        public System.Threading.Tasks.Task SchimbaProprietateAsync(string nume, string valoare)
        {
            return base.Channel.SchimbaProprietateAsync(nume, valoare);
        }
        
        public System.Threading.Tasks.Task StergePozaAsync(string path)
        {
            return base.Channel.StergePozaAsync(path);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceReferencePhotos.DTO>> CautareAsync(string nume, string valoare)
        {
            return base.Channel.CautareAsync(nume, valoare);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceReferencePhotos.DTO>> GetAllPhotosAsync()
        {
            return base.Channel.GetAllPhotosAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceReferencePhotos.Proprietati>> GetAllPropAsync()
        {
            return base.Channel.GetAllPropAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceReferencePhotos.Proprietati>> CautarePropPhotoAsync(int id)
        {
            return base.Channel.CautarePropPhotoAsync(id);
        }
        
        public System.Threading.Tasks.Task<int> MaxIdMediaAsync()
        {
            return base.Channel.MaxIdMediaAsync();
        }
        
        public System.Threading.Tasks.Task<int> MaxIdPropAsync()
        {
            return base.Channel.MaxIdPropAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_InterfaceApi))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_InterfaceApi))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8000/PC");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return InterfaceApiClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_InterfaceApi);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return InterfaceApiClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_InterfaceApi);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_InterfaceApi,
        }
    }
}
