//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPhotosP2
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTO", Namespace="http://schemas.datacontract.org/2004/07/MyPhotosP2", IsReference=true)]
    public partial class DTO : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        private string PathField;
        
        private string PozaSauVideoField;
        
        private string StersField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Path
        {
            get
            {
                return this.PathField;
            }
            set
            {
                this.PathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PozaSauVideo
        {
            get
            {
                return this.PozaSauVideoField;
            }
            set
            {
                this.PozaSauVideoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sters
        {
            get
            {
                return this.StersField;
            }
            set
            {
                this.StersField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="InterfaceApi")]
public interface InterfaceApi
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceApi/PreluarePoza", ReplyAction="http://tempuri.org/InterfaceApi/PreluarePozaResponse")]
    void PreluarePoza(string path);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceApi/PreluarePoza", ReplyAction="http://tempuri.org/InterfaceApi/PreluarePozaResponse")]
    System.Threading.Tasks.Task PreluarePozaAsync(string path);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceApi/AdaugaProprietate", ReplyAction="http://tempuri.org/InterfaceApi/AdaugaProprietateResponse")]
    void AdaugaProprietate(string path, string nume, string valoare);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceApi/AdaugaProprietate", ReplyAction="http://tempuri.org/InterfaceApi/AdaugaProprietateResponse")]
    System.Threading.Tasks.Task AdaugaProprietateAsync(string path, string nume, string valoare);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceApi/StergeProprietate", ReplyAction="http://tempuri.org/InterfaceApi/StergeProprietateResponse")]
    void StergeProprietate(string path, string nume, string valoare);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceApi/StergeProprietate", ReplyAction="http://tempuri.org/InterfaceApi/StergeProprietateResponse")]
    System.Threading.Tasks.Task StergeProprietateAsync(string path, string nume, string valoare);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceApi/SchimbaProprietate", ReplyAction="http://tempuri.org/InterfaceApi/SchimbaProprietateResponse")]
    void SchimbaProprietate(string nume, string valoare);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceApi/SchimbaProprietate", ReplyAction="http://tempuri.org/InterfaceApi/SchimbaProprietateResponse")]
    System.Threading.Tasks.Task SchimbaProprietateAsync(string nume, string valoare);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceApi/StergePoza", ReplyAction="http://tempuri.org/InterfaceApi/StergePozaResponse")]
    void StergePoza(string path);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceApi/StergePoza", ReplyAction="http://tempuri.org/InterfaceApi/StergePozaResponse")]
    System.Threading.Tasks.Task StergePozaAsync(string path);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceApi/Cautare", ReplyAction="http://tempuri.org/InterfaceApi/CautareResponse")]
    MyPhotosP2.DTO[] Cautare(string nume, string valoare);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceApi/Cautare", ReplyAction="http://tempuri.org/InterfaceApi/CautareResponse")]
    System.Threading.Tasks.Task<MyPhotosP2.DTO[]> CautareAsync(string nume, string valoare);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceApi/MaxIdMedia", ReplyAction="http://tempuri.org/InterfaceApi/MaxIdMediaResponse")]
    int MaxIdMedia();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceApi/MaxIdMedia", ReplyAction="http://tempuri.org/InterfaceApi/MaxIdMediaResponse")]
    System.Threading.Tasks.Task<int> MaxIdMediaAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceApi/MaxIdProp", ReplyAction="http://tempuri.org/InterfaceApi/MaxIdPropResponse")]
    int MaxIdProp();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceApi/MaxIdProp", ReplyAction="http://tempuri.org/InterfaceApi/MaxIdPropResponse")]
    System.Threading.Tasks.Task<int> MaxIdPropAsync();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface InterfaceApiChannel : InterfaceApi, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class InterfaceApiClient : System.ServiceModel.ClientBase<InterfaceApi>, InterfaceApi
{
    
    public InterfaceApiClient()
    {
    }
    
    public InterfaceApiClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public InterfaceApiClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public InterfaceApiClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public InterfaceApiClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public void PreluarePoza(string path)
    {
        base.Channel.PreluarePoza(path);
    }
    
    public System.Threading.Tasks.Task PreluarePozaAsync(string path)
    {
        return base.Channel.PreluarePozaAsync(path);
    }
    
    public void AdaugaProprietate(string path, string nume, string valoare)
    {
        base.Channel.AdaugaProprietate(path, nume, valoare);
    }
    
    public System.Threading.Tasks.Task AdaugaProprietateAsync(string path, string nume, string valoare)
    {
        return base.Channel.AdaugaProprietateAsync(path, nume, valoare);
    }
    
    public void StergeProprietate(string path, string nume, string valoare)
    {
        base.Channel.StergeProprietate(path, nume, valoare);
    }
    
    public System.Threading.Tasks.Task StergeProprietateAsync(string path, string nume, string valoare)
    {
        return base.Channel.StergeProprietateAsync(path, nume, valoare);
    }
    
    public void SchimbaProprietate(string nume, string valoare)
    {
        base.Channel.SchimbaProprietate(nume, valoare);
    }
    
    public System.Threading.Tasks.Task SchimbaProprietateAsync(string nume, string valoare)
    {
        return base.Channel.SchimbaProprietateAsync(nume, valoare);
    }
    
    public void StergePoza(string path)
    {
        base.Channel.StergePoza(path);
    }
    
    public System.Threading.Tasks.Task StergePozaAsync(string path)
    {
        return base.Channel.StergePozaAsync(path);
    }
    
    public MyPhotosP2.DTO[] Cautare(string nume, string valoare)
    {
        return base.Channel.Cautare(nume, valoare);
    }
    
    public System.Threading.Tasks.Task<MyPhotosP2.DTO[]> CautareAsync(string nume, string valoare)
    {
        return base.Channel.CautareAsync(nume, valoare);
    }
    
    public int MaxIdMedia()
    {
        return base.Channel.MaxIdMedia();
    }
    
    public System.Threading.Tasks.Task<int> MaxIdMediaAsync()
    {
        return base.Channel.MaxIdMediaAsync();
    }
    
    public int MaxIdProp()
    {
        return base.Channel.MaxIdProp();
    }
    
    public System.Threading.Tasks.Task<int> MaxIdPropAsync()
    {
        return base.Channel.MaxIdPropAsync();
    }
}
